config/routes.rb
BomManager::Application.routes.draw do
  resources :assembly_items

  resources :assemblies

  root :to => "home#index"

  resources :vendor_parts

  resources :parts

  resources :agents

  resources :vendors

  resources :distributors

end

app/models/distributor.rb
class Distributor < ActiveRecord::Base
  attr_accessible :email, :name, :phone
  has_and_belongs_to_many :vendors
  has_many :agents
end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController
  # GET /distributors
  # GET /distributors.json
  def index
    @distributors = Distributor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @distributors }
    end
  end

  # GET /distributors/1
  # GET /distributors/1.json
  def show
    @distributor = Distributor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @distributor }
    end
  end

  # GET /distributors/new
  # GET /distributors/new.json
  def new
    @distributor = Distributor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @distributor }
    end
  end

  # GET /distributors/1/edit
  def edit
    @distributor = Distributor.find(params[:id])
  end

  # POST /distributors
  # POST /distributors.json
  def create
    @distributor = Distributor.new(params[:distributor])

    respond_to do |format|
      if @distributor.save
        format.html { redirect_to @distributor, :notice => 'Distributor was successfully created.' }
        format.json { render :json => @distributor, :status => :created, :location => @distributor }
      else
        format.html { render :action => "new" }
        format.json { render :json => @distributor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /distributors/1
  # PUT /distributors/1.json
  def update
    @distributor = Distributor.find(params[:id])

    respond_to do |format|
      if @distributor.update_attributes(params[:distributor])
        format.html { redirect_to @distributor, :notice => 'Distributor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @distributor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /distributors/1
  # DELETE /distributors/1.json
  def destroy
    @distributor = Distributor.find(params[:id])
    @distributor.destroy

    respond_to do |format|
      format.html { redirect_to distributors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/views/distributors/_form.html.erb
<%= form_for @distributor, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                distributors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/distributors/edit.html.erb
<%- model_class = Distributor -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/distributors/index.html.erb
<%- model_class = Distributor -%>
<div class="page-header">
  <h1 class="pull-left"><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <div class="btn-group pull-right">
    <%= link_to t('.new', :default => t("helpers.links.new")),
            new_distributor_path,
            :class => 'btn btn-primary' %>
  </div>
  <div class="clearfix"></div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @distributors.each do |distributor| %>
      <tr>
        <td><%= link_to distributor.id, distributor_path(distributor) %></td>
        <td><%= distributor.name %></td>
        <td><%= distributor.phone %></td>
        <td><%= distributor.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_distributor_path(distributor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      distributor_path(distributor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/distributors/new.html.erb
<%- model_class = Distributor -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/distributors/show.html.erb
<%- model_class = Distributor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @distributor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @distributor.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @distributor.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              distributors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_distributor_path(@distributor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              distributor_path(@distributor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>