config/routes.rb
BomManager::Application.routes.draw do
  resources :assembly_items

  resources :assemblies

  root :to => "home#index"

  resources :vendor_parts

  resources :parts

  resources :agents

  resources :vendors

  resources :distributors

end

app/models/vendor_part.rb
class VendorPart < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :part
  attr_accessible :part_number, :vendor_id, :part_id
end

app/controllers/vendor_parts_controller.rb
class VendorPartsController < ApplicationController
  # GET /vendor_parts
  # GET /vendor_parts.json
  def index
    @vendor_parts = VendorPart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @vendor_parts }
    end
  end

  # GET /vendor_parts/1
  # GET /vendor_parts/1.json
  def show
    @vendor_part = VendorPart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @vendor_part }
    end
  end

  # GET /vendor_parts/new
  # GET /vendor_parts/new.json
  def new
    @vendor_part = VendorPart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @vendor_part }
    end
  end

  # GET /vendor_parts/1/edit
  def edit
    @vendor_part = VendorPart.find(params[:id])
  end

  # POST /vendor_parts
  # POST /vendor_parts.json
  def create
    @vendor_part = VendorPart.new(params[:vendor_part])

    respond_to do |format|
      if @vendor_part.save
        format.html { redirect_to @vendor_part, :notice => 'Vendor part was successfully created.' }
        format.json { render :json => @vendor_part, :status => :created, :location => @vendor_part }
      else
        format.html { render :action => "new" }
        format.json { render :json => @vendor_part.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vendor_parts/1
  # PUT /vendor_parts/1.json
  def update
    @vendor_part = VendorPart.find(params[:id])

    respond_to do |format|
      if @vendor_part.update_attributes(params[:vendor_part])
        format.html { redirect_to @vendor_part, :notice => 'Vendor part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @vendor_part.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vendor_parts/1
  # DELETE /vendor_parts/1.json
  def destroy
    @vendor_part = VendorPart.find(params[:id])
    @vendor_part.destroy

    respond_to do |format|
      format.html { redirect_to vendor_parts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vendor_parts_helper.rb
module VendorPartsHelper
end

app/views/vendor_parts/_form.html.erb
<%= form_for @vendor_part, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :vendor_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :vendor_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :part_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :part_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :part_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :part_number, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                vendor_parts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/vendor_parts/edit.html.erb
<%- model_class = VendorPart -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vendor_parts/index.html.erb
<%- model_class = VendorPart -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:vendor_id) %></th>
      <th><%= model_class.human_attribute_name(:part_id) %></th>
      <th><%= model_class.human_attribute_name(:part_number) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vendor_parts.each do |vendor_part| %>
      <tr>
        <td><%= link_to vendor_part.id, vendor_part_path(vendor_part) %></td>
        <td><%= vendor_part.vendor.name %></td>
        <td><%= vendor_part.part.title %></td>
        <td><%= vendor_part.part_number %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vendor_part_path(vendor_part), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vendor_part_path(vendor_part),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vendor_part_path,
            :class => 'btn btn-primary' %>

app/views/vendor_parts/new.html.erb
<%- model_class = VendorPart -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vendor_parts/show.html.erb
<%- model_class = VendorPart -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:vendor_id) %>:</strong></dt>
  <dd><%= @vendor_part.vendor_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:part_id) %>:</strong></dt>
  <dd><%= @vendor_part.part_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:part_number) %>:</strong></dt>
  <dd><%= @vendor_part.part_number %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              vendor_parts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vendor_part_path(@vendor_part), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vendor_part_path(@vendor_part),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>