config/routes.rb
BomManager::Application.routes.draw do
  resources :assembly_items

  resources :assemblies

  root :to => "home#index"

  resources :vendor_parts

  resources :parts

  resources :agents

  resources :vendors

  resources :distributors

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= t('.title') %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><%= t('.title') %></a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to t('.parts'), parts_path %></li>
              <li><%= link_to t('.assemblies'), assemblies_path %></li>
              <li><%= link_to t('.vendors'), vendors_path %></li>
              <li><%= link_to t('.distributors'), distributors_path %></li>
              <li><%= link_to t('.agents'), agents_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
            <%= yield %>  
        </div><!--/row-->
      </div><!--/content-->

    </div> <!-- /container -->
    <footer>
      <div class="container">
        <p class="muted credit">BOM Manager. A courtesy of <a href="http://github.com/derekstavis">Derek Stavis</a>, <a href="http://github.com/maiconchaves">Maicon Chaves</a> and <a href="http://dba.eng.br">DBA Technology</a>.</p>
      </div>
    </footer>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>